name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Extract changelog
      id: changelog
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        sed -n "/^## \[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '1d;$d' > release_notes.txt
        if [ ! -s release_notes.txt ]; then
          echo "Release $VERSION" > release_notes.txt
        fi
        cat release_notes.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release_notes.txt
        generate_release_notes: false

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
